aistudio_token : '{your_token}'      # 文心一言的token
dashscope_api_key : '{your_api_key}' # 通义千问的api_key
zhiouai_api_key : '{your_api_key}'   # 智谱AI的密钥

# 星火大模型配置
appid : "{}"       # 填写控制台中获取的 APPID 信息
api_secret : "{}"  # 填写控制台中获取的 APISecret 信息
api_key : "{}"     # 填写控制台中获取的 APIKey 信息


system : '现在你是一个心理专家，我有一些心理问题，请你用专业的知识帮我解决'
emotions_list : [
        "钦佩",
        "崇拜",
        "欣赏",
        "娱乐",
        "焦虑",
        "敬畏",
        "尴尬",
        "厌倦",
        "冷静",
        "困惑",
        "渴望",
        "厌恶",
        "同情",
        "痛苦",
        "着迷",
        "嫉妒",
        "兴奋",
        "恐惧",
        "痛恨",
        "有趣",
        "快乐",
        "怀旧",
        "浪漫",
        "悲伤",
        "满意",
        "性欲",
        "同情",
        "满足"
    ]
areas_of_life : [
    "工作",
    "学业",
    "生活",
    "身体",
    "家人",
    "朋友",
    "社交",
    "恋爱",
    "就业",
    "责任",
    "爱好",
    "环境",
    "隐私",
    "安全",
    "梦想",
    "自由"
]
